AWSTemplateFormatVersion: 2010-09-09
Description: CFn VPC for RailsAP

Resources:
  CFnVPCforRails:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 192.168.0.0/16
      InstanceTenancy: default
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: CFnVPCForRails

  CFnPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.1.0/24
      VpcId: !Ref CFnVPCforRails
      AvailabilityZone: !Sub ${AWS::Region}a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub PublicSubnet-${AWS::Region}a

  CFnPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.2.0/24
      VpcId: !Ref CFnVPCforRails
      AvailabilityZone: !Sub ${AWS::Region}c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub PublicSubnet-${AWS::Region}c

  CFnPrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.11.0/24
      VpcId: !Ref CFnVPCforRails
      AvailabilityZone: !Sub ${AWS::Region}a
      Tags:
        - Key: Name
          Value: !Sub PrivateSubnet-${AWS::Region}a

  CFnPrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 192.168.12.0/24
      VpcId: !Ref CFnVPCforRails
      AvailabilityZone: !Sub ${AWS::Region}c
      Tags:
        - Key: Name
          Value: !Sub PrivateSubnet-${AWS::Region}c

  CFnVPCIGWforRails:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags:
        - Key: Name
          Value: CFn-VPCIGWforRails

  CFnVPCIGWAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref CFnVPCIGWforRails
      VpcId: !Ref CFnVPCforRails

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref CFnVPCforRails
      Tags:
        - Key: Name
          Value: PublicRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    # DependsOn: CFnVPCIGWforRails
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref CFnVPCIGWforRails

  PublicSubnet1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CFnPublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref CFnPublicSubnet2
      RouteTableId: !Ref PublicRouteTable

Outputs:
  VPCID:
    Description: VPC ID
    Value: !Ref CFnVPCforRails
    Export:
      Name: CFnVPCforRails-VPCID

  PublicSubnet1:
    Description: CFnPublicSubnet1
    Value: !Ref CFnPublicSubnet1
    Export:
      Name: !Sub PublicSubnet-${AWS::Region}a

  PublicSubnet2:
    Description: CFnPublicSubnet2
    Value: !Ref CFnPublicSubnet2
    Export:
      Name: !Sub PublicSubnet-${AWS::Region}c

  PrivateSubnet1:
    Description: CFnPrivateSubnet1
    Value: !Ref CFnPrivateSubnet1
    Export:
      Name: !Sub PrivateSubnet-${AWS::Region}a

  PrivateSubnet2:
    Description: CFnPrivateSubnet2
    Value: !Ref CFnPrivateSubnet2
    Export:
      Name: !Sub PrivateSubnet-${AWS::Region}c